### ISSUE TITLE
"Type 'GraphQLSchema' is not assignable to type 'GraphQLSchema'. Two different types with this name exist, but they are unrelated."

### ISSUE THREAD

**Issue by brukh** [adrien2p/nest-js-graphql#2]
Hi, I was going through the example and encountered this exception within `graphql.service.ts`.
<img width="967" alt="ss" src="https://user-images.githubusercontent.com/2824573/32631670-90c84664-c566-11e7-8aab-3993389b3a79.png">

Adding `after public get schema() : any` removes the exception but since I am fairly new to TypeScript I was having issues resolving it using the interface. 

Thanks for the help!

**Comment by adrien2p** [comment]
Hey ! I’ll take a look as soon as i can and

**Comment by adrien2p** [comment]
Hey @brukh i can't reproduce this error, could you paste your import ?

**Comment by adrien2p** [comment]
Any news ?

**Comment by brukh** [comment]
Hi @adrien2p! I attached a screenshot of the stack trace but you might have to remove your node modules and reinstall to reproduce. I just cloned the repo and did an install and got the error. Thanks for looking into it.

<img width="715" alt="screen shot 2017-11-17 at 12 49 41 am" src="https://user-images.githubusercontent.com/2824573/32934546-a557de2a-cb31-11e7-9339-f0220f02a981.png">

**Comment by adrien2p** [comment]
hey @brukh i have re tried, i removed all my node modules and reinstall them but i don't have any error. 
<img width="1399" alt="screen shot 2017-11-20 at 09 14 05" src="https://user-images.githubusercontent.com/25098370/33008388-336e081c-cdd3-11e7-8fd7-4d2e8fb6d73e.png">
