### ISSUE TITLE
Setting Subscriptions up 

### ISSUE THREAD

**Issue by cameronrll** [adrien2p/nest-js-graphql#3]
Hi there,

Just wondering how to go about setting up a websockets endpoint to use with subscriptions?
Am struggling to figure out where I would need to put the WS server, for example if I set it up in the server.ts file I won't have access to the schema or resolvers, however if I set it up in the graphql controller I don't have access to the express server. I assume I am missing something obvious here, I really like the style used in this project and am trying to stick to it within my own. 

Any help with resolving this issue would be greatly appreciated.

**Comment by adrien2p** [comment]
Hi @cameronrll,

If i understand what you need, it's to access the server instance, if it's that you should use `@WebSocketServer() server` to get the access to the server, but is still passed to the`onGatewayIni`.

I hope that can help you, this is the link to the [gateways documentation](https://docs.nestjs.com/websockets/gateways), if you need something else i'll be happy to help you.

Just one think, i need to take the time to update the packages of all my nest repo's.
