### ISSUE TITLE
TSError: ⨯ Unable to compile TypeScript

### ISSUE THREAD

**Issue by akshaykumar12527** [adrien2p/nest-js-graphql#5]
I am getting this error while running project

src/modules/graphql/graphql.service.ts (20,9): Type 'GraphQLSchema' is not assignable to type 'GraphQLSchema'. Two different types with this name exist, but they are unrelated.
  Types of property 'getQueryType' are incompatible.
    Type '() => GraphQLObjectType' is not assignable to type '() => GraphQLObjectType'. Two different types with this name exist, but they are unrelated.
      Type 'GraphQLObjectType' is not assignable to type 'GraphQLObjectType'. Two different types with this name exist, but they are unrelated.
        Property 'extensionASTNodes' is missing in type 'GraphQLObjectType'. (90010)

**Comment by VRspace4** [comment]
I've gotten it to work by matching the @types/graphql version with the one being used in graphql-tools, which was using v0.9.4.

So an `npm install @types/graphql@0.9.4` did the trick for me.
